---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: bosh/main-ruby-go

inputs:
  - name: bosh-cli
  - name: bosh-dev-release
  - name: bosh-deployment
  - name: bosh-src

params: []

run:
  path: bosh-src/ci/tasks/deploy-docker-director.sh
