---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: bosh/blobstore_client

inputs:
  - name: bosh-src

run:
  path: bosh-src/ci/tasks/test-local-blobstore-client-integration.sh

params:
