---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: bosh/main-bosh-docker

inputs:
  - name: bosh-src
  - name: bosh-dns-release
  - name: candidate-warden-ubuntu-stemcell
  - name: bosh-release

run:
  path: bosh-src/ci/tasks/test-brats.sh
