---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/bosh-lite-ci

inputs:
- name: bosh-src
- name: published-stemcell
run:
  path: bosh-src/ci/pipelines/stemcells/tasks/make-stemcell-version.sh
