---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: bosh/compiled-release

inputs:
  - name: bosh-src
  - name: bosh-deployment

outputs:
  - name: director-state

run:
  path: bosh-src/ci/pipelines/compiled-releases/tasks/deploy-director.sh

params:
  BOSH_access_key_id: required
  BOSH_secret_access_key: required
  BOSH_private_key: required
  BOSH_TARGET_IP: required
  BOSH_RESERVED_RANGES: required
