---
groups:
  - name: bosh-aws-ubuntu-bats
    jobs:
      - ubuntu-bats
jobs:
  - name: ubuntu-bats
    max_in_flight: 3
    plan:
    - do:
      - aggregate:
        - {get: stemcell,      trigger: true, resource: ubuntu-stemcell}
        - {get: bosh-release,  trigger: true, resource: bosh-candidate-release-tarballs}
        - {get: cpi-release,   trigger: true}
        - {get: bats,          trigger: false}
        - {get: bosh-cli,      trigger: false}
        - {get: bosh-src,      trigger: false}
        - {get: certification, trigger: false}

      - task: prepare-director
        file: certification/aws/tasks/prepare-director.yml
        input_mapping: {pipelines: certification}
        params:
            BOSH_USER:              {{BOSH_DIRECTOR_USERNAME}}
            BOSH_PASSWORD:          {{BOSH_DIRECTOR_PASSWORD}}
            AWS_ACCESS_KEY:         {{aws_access_key__primary}}
            AWS_SECRET_KEY:         {{aws_secret_key__primary}}
            AWS_REGION_NAME:        {{aws_region__primary}}
            PUBLIC_KEY_NAME:        {{bats_pipeline_public_key_name}}
            PRIVATE_KEY_DATA:       {{bats_pipeline_private_key}}

      - do:
        - task: deploy-director
          file: certification/shared/tasks/deploy-director.yml
          input_mapping: {pipelines: certification}
          params:
            BOSH_DIRECTOR_USERNAME: {{BOSH_DIRECTOR_USERNAME}}
            BOSH_DIRECTOR_PASSWORD: {{BOSH_DIRECTOR_PASSWORD}}

        - task: prepare-manual-bats
          file: certification/aws/tasks/prepare-manual-bats.yml
          input_mapping: {pipelines: certification}
          params:
            AWS_ACCESS_KEY:         {{aws_access_key__primary}}
            AWS_SECRET_KEY:         {{aws_secret_key__primary}}
            AWS_REGION_NAME:        {{aws_region__primary}}
            BAT_VCAP_PASSWORD:      {{BAT_VCAP_PASSWORD}}
            PUBLIC_KEY_NAME:        {{bats_pipeline_public_key_name}}
            BOSH_USER:              {{BOSH_DIRECTOR_USERNAME}}
            BOSH_PASSWORD:          {{BOSH_DIRECTOR_PASSWORD}}
            STEMCELL_NAME:          bosh-aws-xen-hvm-ubuntu-trusty-go_agent

        - task: run-bats
          file: certification/shared/tasks/run-bats.yml
          input_mapping: {pipelines: certification}

        ensure:
          do:
          - task: teardown
            file: certification/shared/tasks/teardown.yml
            input_mapping: {pipelines: certification}
            params:
              DEPLOYMENT_NAME:        certification

resources:
  - name: bosh-src
    type: git
    source:
      uri: https://github.com/cloudfoundry/bosh.git
      branch: develop

  - name: cpi-release
    type: bosh-io-release
    source:
      repository: cloudfoundry-incubator/bosh-aws-cpi-release

  - name: bosh-cli
    type: s3
    source:
      regexp: bosh-cli-([0-9.]+)-linux-amd64
      bucket: bosh-cli-artifacts
      region_name: us-east-1

  - name: certification
    type: git
    source:
      uri: https://github.com/zaksoup/bosh-cpi-certification
      branch: master

  - name: ubuntu-stemcell
    type: bosh-io-stemcell
    source:
      name: bosh-aws-xen-hvm-ubuntu-trusty-go_agent
  - name: bosh-candidate-release-tarballs
    type: s3
    source:
      bucket: {{candidate_release_bucket}}
      regexp: "bosh.*\\+dev\\.(\\d+)\\.tgz" # bosh-257.9+dev.1472844900.tgz

  - name: bats
    type: git
    source:
      uri: https://github.com/cloudfoundry/bosh-acceptance-tests.git
      branch: master
