---
groups:
  - name: all
    jobs:
      - build-stemcell
      #- publish-stemcells
      - build-openstack-kvm-ubuntu-trusty
  - name: openstack
    jobs:
      - build-openstack-kvm-ubuntu-trusty
  - name: ubuntu
    jobs:
      - build-openstack-kvm-ubuntu-trusty
jobs:
  - name: build-stemcell
    serial: true
    plan:
      - get: bosh-src
      - get: version
        params:
          bump: {{stemcell_version_semver_bump}}
      - put: version
        params:
          file: version/number

#  - name: publish-stemcells
#    serial: true
#    plan:
#      - aggregate:
#        - get: version
#          trigger: true
#          passed: [test-stemcells]
#        - get: bosh-src
#          passed: [test-stemcells]
#      - task: copy-artifacts
#        file: bosh-src/ci/pipelines/stemcell/tasks/publish.yml
#        params:
#          AWS_ACCESS_KEY_ID: {{stemcell_aws_access_key}}
#          AWS_SECRET_ACCESS_KEY: {{stemcell_aws_secret_key}}
#          BUCKET_NAME: {{stemcell_bucket}}
#          CANDIDATE_PREFIX: bosh-stemcell-candidate/
#          PUBLISHED_PREFIX: bosh-stemcell/
#          COPY_KEYS: |
#            openstack/bosh-stemcell-%s-openstack-kvm-ubuntu-trusty-go_agent.tgz
#            openstack/bosh-stemcell-%s-openstack-kvm-ubuntu-trusty-go_agent-raw.tgz
#      - task: tag
#        file: bosh-src/ci/pipelines/stemcell/tasks/tag.yml
#      - put: bosh-src-push
#        params:
#          repository: bosh-src-tagged
#          only_tag: true


  #
  # OpenStack
  #

  - name: build-openstack-kvm-ubuntu-trusty
    plan:
      - aggregate:
          - get: version
            trigger: true
            passed: [build-stemcell]
          - get: bosh-src
            passed: [build-stemcell]
          - get: os-image-stemcell-builder
      - task: create-stemcell
        file: bosh-src/ci/pipelines/stemcell/tasks/build.yml
        image: os-image-stemcell-builder
        privileged: true
        params:
          IAAS:         openstack
          HYPERVISOR:   kvm
          OS_NAME:      ubuntu
          OS_VERSION:   trusty
         # BOSHIO_TOKEN: {{boshio_checksum_token}}
      - aggregate:
        - put: openstack-kvm-ubuntu-trusty-raw
          params:
            file: stemcell/*-raw.tgz
        - put: openstack-kvm-ubuntu-trusty
          params:
            file: stemcell/*-go_agent.tgz

resources:

  - name: os-image-stemcell-builder
    type: docker-image
    source:
      repository: 140.211.168.97:5000/os-image-stemcell-builder
      insecure_registries: ["140.211.168.97:5000"]
      username: {{username}}
      password: {{password}}
#  - name: bosh-src-push
#    type: git
#    source:
#      uri: bosh_src_push_url
#      branch: {{stemcell-branch}}
#      private_key: {{bosh_src_key}}

  - name: bosh-src
    type: git
    source:
      uri: {{bosh_src_url}}
      branch: {{stemcell-branch}}

  - name: version
    type: semver
    source:
      initial_version: 3238.0.0
      driver: s3
      key: {{stemcell_version_key}}
      bucket: {{stemcell_bucket}}
      access_key_id: {{stemcell_aws_access_key}}
      secret_access_key: {{stemcell_aws_secret_key}}

  - name: syslog-release
    type: bosh-io-release
    source:
      repository: cloudfoundry/syslog-release

  #
  # OpenStack
  #

  - name: openstack-kvm-ubuntu-trusty
    type: s3
    source:
      bucket: {{stemcell_bucket}}
      regexp: bosh-stemcell-candidate/openstack/bosh-stemcell-(.+)-openstack-kvm-ubuntu-trusty-go_agent.tgz
      access_key_id: {{stemcell_aws_access_key}}
      secret_access_key: {{stemcell_aws_secret_key}}

  - name: openstack-kvm-ubuntu-trusty-raw
    type: s3
    source:
      bucket: {{stemcell_bucket}}
      regexp: bosh-stemcell-candidate/openstack/bosh-stemcell-(.+)-openstack-kvm-ubuntu-trusty-go_agent-raw.tgz
      access_key_id: {{stemcell_aws_access_key}}
      secret_access_key: {{stemcell_aws_secret_key}}


resource_types:
- name: semver
  type: docker-image
  source:
    repository: 140.211.168.97:5000/semver-resource
    insecure_registries: ["140.211.168.97:5000"]
    username: {{username}}
    password: {{password}}