---
jobs:
  - name: start-job
    serial: true
    plan:
      - get: bosh-src
        trigger: false

  - name: build-ubuntu-trusty
    plan:
      - get: bosh-src
        trigger: true
        passed:
          - start-job
      - get: os-image-stemcell-builder
      - task: build
        file: bosh-src/ci/pipelines/os-images-new/tasks/build.yml
        image: os-image-stemcell-builder
        privileged: true
        params:
          OPERATING_SYSTEM_NAME:      ubuntu
          OPERATING_SYSTEM_VERSION:   trusty
      - put: ubuntu-trusty-tarball
        params:
          file: os-image/ubuntu-trusty.tgz
          acl: public-read

resources:

  - name: os-image-stemcell-builder
    type: docker-image
    source:
      repository: 140.211.168.97:5000/os-image-stemcell-builder
      insecure_registries: ["140.211.168.97:5000"]
      username: {{username}}
      password: {{password}}

  - name: bosh-src
    type: git
    source:
      uri: {{bosh_src_url}}
      branch: {{stemcell-branch}}

  #
  # ubuntu-trusty
  #

  - name: ubuntu-trusty-tarball
    type: s3
    source:
      bucket: {{osimage_bucket}}
      versioned_file: bosh-ubuntu-trusty-os-image.tgz
      access_key_id: {{osimage_aws_access_key}}
      secret_access_key: {{osimage_aws_secret_key}}