---
name: Test Director
port: 8081

logging:
  level: ERROR

dir: /tmp/boshdir
db:
  adapter: sqlite
  database: '/:memory:'
  connection_options:
    max_connections: 32
    pool_timeout: 10
verify_multidigest_path: /some/path
blobstore:
  provider: davcli
  options:
    endpoint: http://127.0.0.1
    user: admin
    password:
    davcli_path: true
local_dns:
  enabled: false
  include_index: false
compiled_package_cache:
  provider: local
  options:
    blobstore_path: /path/to/some/bucket
snapshots:
  enabled: false
scan_and_fix:
  auto_fix_stateful_nodes: false
cloud:
  plugin: dummy
  properties:
    dir: ...
     # to be added
backup_destination:
  provider: s3cli
  options:
    bucket_name: foo
    access_key_id: asdf
    secret_access_key: zxcv
    s3cli_path: true
user_management:
  provider: local
  local:
    users:
    - {name: admin, password: admin}
config_server:
  enabled: false
record_events: true
version: '0.0.2'
mbus: 'nats://some-user:some-pass@some-nats-uri:1234'

nats:
  server_ca_path: '/path/to/server_ca_path'
  client_certificate_path: '/path/to/director_certificate_path'
  client_private_key_path: '/path/to/director_private_key_path'
  client_ca_certificate_path: '/path/to/client_ca_certificate_path'
  client_ca_private_key_path: '/path/to/client_ca_private_key_path'
