---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: boshcpi/aws-cpi-release

inputs:
- name: bosh-src

outputs:
- name: release

run:
  path: bosh-src/ci/pipelines/alpha-releases/tasks/make.sh
